version: '3.9'

services:
  db:
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'erbandanaj'
      POSTGRES_PASSWORD: 'think'
      POSTGRES_DB: 'covid_dashboard'

  server:
    build: .
    ports:
      - '5000:5000'
      - '5555:5555'
    command: ["/bin/bash", "./startup.sh"]
    env_file:
      - .env

  client:
    build: ./client
    ports:
      - '3000:3000'
    command: npm run start
    env_file:
      - .env